apiVersion: v1
kind: Service
metadata:
  name: {{ template "helloworld.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "helloworld.name" . }}
    helm.sh/chart: {{ include "helloworld.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ template "helloworld.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

